(source gnu)
(source melpa)

(package-file "kuso-base.el")
(package "kuso-base" "1.0.0" "Kuso Base plugin which contain basic configuration of Kuso"))

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))

(depends-on "powerline")
(depends-on "color-theme")
(depends-on "key-chord")
(depends-on "color-theme-monokai")
(depends-on "es-lib")
(depends-on "es-windows")
(depends-on "ido-vertical-mode")
;(depends-on "workgroups")
(depends-on "hideshow-org")
(depends-on "dired+")
(depends-on "multiple-cursors")
(depends-on "expand-region")
(depends-on "flx-ido")
